#!/bin/sh

# Regenerate src/Makevars.in, src/Makevars.win and src/Makevars.ucrt from the
# authoritative source-list files under tools/.
#
# The bundled NNG and Mbed TLS sources are compiled directly into nanonext.so
# via explicit per-object make rules -- no cmake, no static archives, no install
# step. This script is the single source of truth for those rules: it is invoked
# by tools/update_nng.sh and tools/update_mbedtls.sh after a vendoring refresh,
# and may be run by hand. The three Makevars are GENERATED ARTIFACTS and carry a
# "do not edit by hand" banner; edit the tools/*.list inputs instead.
#
# The shared rule block (all nng-common + mbedtls objects) is emitted byte for
# byte into all three Makevars, so the common recipes cannot drift across files.
# Only the platform block (posix vs windows) and the per-OS preamble differ.

set -e

PKG_ROOT=$(cd "$(dirname "$0")/.." && pwd)
TOOLS="$PKG_ROOT/tools"
SRC="$PKG_ROOT/src"

# --- Windows fixed flags (no configure step on Windows) ----------------------
# NNG defines for the bundled Windows build. Identical common set to POSIX (see
# tools/update_nng.sh / the Phase-0 cmake oracle), plus the fixed Windows
# platform macros. No feature probing: NNG_HAVE_CONDVAR / NNG_HAVE_SNPRINTF are
# cmake-only sanity guards (never referenced in C source) and the NNG_HAVE_STR*
# helpers fall back to NNG's own implementations when undefined.
NNG_COMMON_DEFS='-DNNG_STATIC_LIB -DNNG_PRIVATE -DNNG_SUPP_TLS -DNNG_SUPP_HTTP -DNNG_ENABLE_STATS -DNNG_RESOLV_CONCURRENCY=4 -DNNG_MAX_TASKQ_THREADS=16 -DNNG_MAX_EXPIRE_THREADS=8 -DNNG_MAX_POLLER_THREADS=8 -DNNG_TLS_ENGINE_INIT=nng_tls_engine_init_mbed -DNNG_TLS_ENGINE_FINI=nng_tls_engine_fini_mbed -DNNG_TRANSPORT_INPROC -DNNG_TRANSPORT_IPC -DNNG_TRANSPORT_TCP -DNNG_TRANSPORT_TLS -DNNG_TRANSPORT_WS -DNNG_TRANSPORT_WSS -DNNG_TRANSPORT_FDC -DNNG_HAVE_BUS0 -DNNG_HAVE_PAIR0 -DNNG_HAVE_PAIR1 -DNNG_HAVE_PUB0 -DNNG_HAVE_SUB0 -DNNG_HAVE_PULL0 -DNNG_HAVE_PUSH0 -DNNG_HAVE_REQ0 -DNNG_HAVE_REP0 -DNNG_HAVE_SURVEYOR0 -DNNG_HAVE_RESPONDENT0'
WIN_PLATFORM_DEFS='-DNNG_PLATFORM_WINDOWS -D_WIN32_WINNT=0x0600 -D_CRT_SECURE_NO_WARNINGS -D_CRT_RAND_S'
WIN_LIBS='-lws2_32 -lmswsock -ladvapi32 -lbcrypt -liphlpapi'

# Strip comment/blank lines from a .list file.
read_list() { grep -v '^#' "$1" | grep -v '^[[:space:]]*$'; }

# Join object lines (stdin) into one trimmed, space-separated line.
join_objs() { tr '\n' ' ' | sed 's/  */ /g; s/^ *//; s/ *$//'; }

# Emit one explicit compile rule per object (object paths read from stdin).
# The recipe is identical to R's own .c.o suffix rule with the relevant group's
# *_CPPFLAGS prepended; it names its source explicitly and uses only portable
# make variables, so any POSIX make builds it (no pattern rules, no VPATH, no
# automatic-variable source refs).
emit_rules() {
  while IFS= read -r obj; do
    case "$obj" in
      ''|\#*) continue ;;
    esac
    src=$(printf '%s' "$obj" | sed 's/\.o$/.c/')
    case "$obj" in
      '$(MBED)'*) grp='$(MBED_CPPFLAGS)' ;;
      *)          grp='$(NNG_CPPFLAGS)' ;;
    esac
    printf '%s: %s\n\t$(CC) %s $(ALL_CPPFLAGS) $(ALL_CFLAGS) -c %s -o $@\n' \
      "$obj" "$src" "$grp" "$src"
  done
}

NNG_COMMON="$TOOLS/nng_common.list"
NNG_POSIX="$TOOLS/nng_posix.list"
NNG_POLLERS="$TOOLS/nng_pollers.list"
NNG_RAND="$TOOLS/nng_rand.list"
NNG_WINDOWS="$TOOLS/nng_windows.list"
MBED="$TOOLS/mbedtls.list"

# ============================================================================
# src/Makevars.in  (POSIX / macOS / wasm template; configure substitutes the
# include flags, defines, link flags and bundled object lists)
# ============================================================================
{
  cat <<'EOF'
# Generated by tools/generate_makevars.sh -- do not edit by hand.
#
# The bundled NNG and Mbed TLS sources are compiled directly into nanonext.so
# (no cmake, no static archive, no install step). configure substitutes:
#   @cppflags@         package include flags (bundled: -Inng/include
#                      -Imbedtls/include -DNNG_STATIC_LIB; system: detected -I)
#   @nng_defs@         mbedtls include + the full NNG -D set (probe-derived)
#   @nng_objects@      bundled NNG objects (empty when a system libnng is used)
#   @mbedtls_objects@  bundled Mbed TLS objects (empty for a system libmbedtls)
#   @libs@             link flags (system libs and/or -lpthread/-latomic/...)
#
# PKG_CFLAGS carries $(C_VISIBILITY) (-fvisibility=hidden) which reaches every
# object via $(ALL_CFLAGS), hiding the bundled nng_*/mbedtls_* symbols.
PKG_CPPFLAGS = @cppflags@
PKG_CFLAGS = $(C_VISIBILITY)
PKG_LIBS = @libs@

MBED = mbedtls/library
NNG = nng/src

MBED_CPPFLAGS = -Imbedtls/include -Imbedtls/library
NNG_CPPFLAGS = -Inng/src -Inng/include @nng_defs@

# Top-level package sources (built by R's own suffix rules)
P_OBJECTS = aio.o comms.o core.o dispatcher.o init.o ncurl.o net.o proto.o server.o sync.o thread.o tls.o utils.o
# Bundled objects (empty when the corresponding system library is used)
NNG_OBJECTS = @nng_objects@
MBEDTLS_OBJECTS = @mbedtls_objects@

OBJECTS = $(P_OBJECTS) $(NNG_OBJECTS) $(MBEDTLS_OBJECTS)

# `all:` MUST be the first target: an explicit object rule below would otherwise
# become make's default goal when R CMD SHLIB invokes make with no target.
all: $(SHLIB)

$(SHLIB): $(OBJECTS)

# --- Explicit compile rules for every possible bundled source ----------------
# Rules are harmless when their object is not in OBJECTS, so configure can pick
# the poller/rand variant without editing rules.
EOF
  # Shared block (nng-common + mbedtls): byte-identical across all 3 Makevars.
  { read_list "$NNG_COMMON"; read_list "$MBED"; } | emit_rules
  # POSIX platform block (always-posix base + every poller/rand variant).
  { read_list "$NNG_POSIX"; read_list "$NNG_POLLERS"; read_list "$NNG_RAND"; } | emit_rules
  printf '\n.PHONY: all clean\nclean:\n\trm -f $(OBJECTS) $(SHLIB)\n'
} > "$SRC/Makevars.in"

# ============================================================================
# src/Makevars.win and src/Makevars.ucrt  (fully static -- no configure step)
# Pure C, so .win (Rtools40, biarch i386+x64) and .ucrt (Rtools42+) are
# identical. Biarch is served by R's native per-sub-arch build.
# ============================================================================
WIN_NNG_OBJECTS=$( { read_list "$NNG_COMMON"; read_list "$NNG_WINDOWS"; } | join_objs )
WIN_MBEDTLS_OBJECTS=$( read_list "$MBED" | join_objs )

write_windows_makevars() {
  out="$1"; rtools="$2"
  {
    printf '# Generated by tools/generate_makevars.sh -- do not edit by hand.\n'
    printf '#\n# %s. The bundled NNG and Mbed TLS sources compile directly into\n' "$rtools"
    printf '# nanonext.dll (no cmake, no static archive). Fully static: Windows needs no\n'
    printf '# feature probing. Biarch is served by R'"'"'s native per-sub-arch build.\n'
    printf '#\n# PKG_CFLAGS carries $(C_VISIBILITY) to hide the bundled nng_*/mbedtls_* symbols.\n'
    printf 'PKG_CPPFLAGS = -Inng/include -Imbedtls/include -DNNG_STATIC_LIB\n'
    printf 'PKG_CFLAGS = $(C_VISIBILITY)\n'
    printf 'PKG_LIBS = %s\n\n' "$WIN_LIBS"
    printf 'MBED = mbedtls/library\n'
    printf 'NNG = nng/src\n\n'
    printf 'MBED_CPPFLAGS = -Imbedtls/include -Imbedtls/library\n'
    printf 'NNG_CPPFLAGS = -Inng/src -Inng/include -Imbedtls/include %s %s\n\n' \
      "$NNG_COMMON_DEFS" "$WIN_PLATFORM_DEFS"
    printf 'P_OBJECTS = aio.o comms.o core.o dispatcher.o init.o ncurl.o net.o proto.o server.o sync.o thread.o tls.o utils.o\n'
    printf 'NNG_OBJECTS = %s\n' "$WIN_NNG_OBJECTS"
    printf 'MBEDTLS_OBJECTS = %s\n\n' "$WIN_MBEDTLS_OBJECTS"
    printf 'OBJECTS = $(P_OBJECTS) $(NNG_OBJECTS) $(MBEDTLS_OBJECTS)\n\n'
    printf 'all: $(SHLIB)\n\n'
    printf '$(SHLIB): $(OBJECTS)\n\n'
    # Shared block (nng-common + mbedtls): byte-identical to Makevars.in.
    { read_list "$NNG_COMMON"; read_list "$MBED"; } | emit_rules
    # Windows platform block.
    read_list "$NNG_WINDOWS" | emit_rules
    printf '\n.PHONY: all clean\nclean:\n\trm -f $(OBJECTS) $(SHLIB)\n'
  } > "$out"
}

write_windows_makevars "$SRC/Makevars.win"  "Rtools40 (gcc 8.3), dual i386 + x64"
write_windows_makevars "$SRC/Makevars.ucrt" "Rtools42/43/44 (UCRT)"

echo "Generated:"
echo "  src/Makevars.in"
echo "  src/Makevars.win"
echo "  src/Makevars.ucrt"
