#!/bin/bash

# Vendor / refresh the bundled NNG sources and regenerate the build files.
#
# Usage:
#   ./tools/update_nng.sh [VERSION]     refresh src/nng from upstream VERSION
#   ./tools/update_nng.sh --verify [VERSION]
#                                       check the committed source lists against
#                                       a fresh cmake "oracle" build (no writes)
#
# The bundled NNG compiles directly into nanonext.so via the per-object rules in
# src/Makevars*. cmake is used here ONLY as the verification oracle for the
# object set (export of compile_commands.json) -- it is not part of the package
# build. This script is the maintenance contract: it derives the authoritative
# tools/nng_*.list source lists from that oracle, applies tools/patch_nng.sh, and
# regenerates the three Makevars via tools/generate_makevars.sh.
#
# The NNG option set must match the package build: all protocols & transports on,
# TLS = mbed, stats on -- these are NNG's CMake defaults, so a plain configure of
# upstream reproduces nanonext's compiled object set.
#
# For offline testing the oracle build dir can be supplied via NNG_ORACLE_DIR
# (must contain compile_commands.json); the upstream clone/cmake steps are then
# skipped.

set -e

# Upstream repo. Override with NNG_REPO=/path/to/local/clone for an offline run.
NNG_REPO="${NNG_REPO:-https://github.com/nanomsg/nng.git}"
# Pinned upstream ref -- update together with the vendored tree. Any git ref
# (tag, branch, or commit) is accepted. This is NNG's 'stable' branch 6 commits
# past the v1.11.0 tag, which carries the sendmsg/readv EINVAL fix (#2244).
NNG_DEFAULT_VERSION="45f8116f2dd1b0438ab77344a75628d77656c61a"

PKG_ROOT=$(cd "$(dirname "$0")/.." && pwd)
TOOLS="$PKG_ROOT/tools"

VERIFY=0
VERSION=""
for arg in "$@"; do
  case "$arg" in
    --verify) VERIFY=1 ;;
    *) VERSION="$arg" ;;
  esac
done
[ -n "$VERSION" ] || VERSION="$NNG_DEFAULT_VERSION"

# Source paths (relative to nng/src) that nanonext does not bundle: the
# deprecated nanomsg compat API, the wolfssl/zerotier back-ends we never build,
# every unit test, and NNG's own CLI tools / test framework. These are removed
# from the staged tree AND filtered from the derived object lists (and from
# --verify), even though a default cmake build compiles them.
PRUNE_RE='^(compat|testing|tools)/|/(zerotier|wolfssl)/|_test\.c$|^nng_legacy\.c$'

# The Mbed TLS engine nanonext always compiles. A default cmake configure has no
# TLS engine (it needs a system Mbed TLS, which we deliberately do not require),
# so the oracle never lists this object -- it is added unconditionally.
TLS_ENGINE_OBJECT='$(NNG)/supplemental/tls/mbedtls/tls.o'

# Normalise a compile_commands.json into the sorted set of bundled objects in
# $(NNG)/<path>.o form (paths relative to nng/src). Reads the build dir's
# compile_commands.json; keeps only sources under the nng src tree (drops the
# repo-root tests/ and demos), prunes per PRUNE_RE, emits one object per line.
oracle_objects() {
  grep '"file"' "$1/compile_commands.json" |
    sed -E 's/.*"file"[[:space:]]*:[[:space:]]*"([^"]+)".*/\1/' |
    grep '/nng/src/' |
    sed -E 's#.*/nng/src/##' |
    grep -E '\.c$' |
    grep -vE "$PRUNE_RE" |
    sed -E 's#\.c$#.o#; s#^#\$(NNG)/#' |
    sort -u
}

# Build the cmake oracle for a checked-out NNG tree into $2.
build_oracle() {
  src=$1; bld=$2
  CC=`"${R_HOME:-$(R RHOME)}/bin/R" CMD config CC 2>/dev/null || echo cc`
  export CC
  cmake -S "$src" -B "$bld" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_BUILD_TYPE=Release >/dev/null 2>&1
}

read_list() { grep -v '^#' "$1" | grep -v '^[[:space:]]*$'; }

# Obtain an oracle build dir (clone + cmake, unless NNG_ORACLE_DIR supplied).
WORK=""
get_oracle_dir() {
  if [ -n "$NNG_ORACLE_DIR" ]; then
    echo "$NNG_ORACLE_DIR"
    return
  fi
  WORK=$(mktemp -d)
  echo "Cloning NNG ($VERSION) ..." >&2
  git clone --quiet "$NNG_REPO" "$WORK/nng"
  git -C "$WORK/nng" checkout --quiet "$VERSION"
  echo "Configuring cmake oracle ..." >&2
  build_oracle "$WORK/nng" "$WORK/build"
  echo "$WORK/build"
}

# Categorise the oracle object set and (re)write tools/nng_*.list. $1 = oracle
# dir, $2 = checked-out NNG src tree (for globbing poller/rand/windows variants).
write_lists() {
  oracle=$1; nngsrc=$2
  objs=$(oracle_objects "$oracle")

  # common = everything not under platform/, plus the always-compiled TLS engine.
  common=$( { printf '%s\n' "$objs" | grep -v '\$(NNG)/platform/'; printf '%s\n' "$TLS_ENGINE_OBJECT"; } | sort -u)
  posix=$(printf '%s\n' "$objs" | grep '\$(NNG)/platform/posix/' | grep -vE 'posix_pollq_|posix_rand_')

  hdr="# Generated by tools/update_nng.sh -- single source of truth for the build.\n# Object paths use the \$(NNG) make variable. Do not edit by hand.\n"

  printf "$hdr%s\n" "$common" > "$TOOLS/nng_common.list"
  printf "$hdr%s\n" "$posix"  > "$TOOLS/nng_posix.list"
  # Poller / rand / windows variants: every variant present in the tree (the
  # build selects one poller + one rand at configure time; rules exist for all).
  { printf "$hdr"; for f in "$nngsrc"/src/platform/posix/posix_pollq_*.c; do
      b=$(basename "$f" .c); printf '$(NNG)/platform/posix/%s.o\n' "$b"; done; } > "$TOOLS/nng_pollers.list"
  { printf "$hdr"; for f in "$nngsrc"/src/platform/posix/posix_rand_*.c; do
      b=$(basename "$f" .c); printf '$(NNG)/platform/posix/%s.o\n' "$b"; done; } > "$TOOLS/nng_rand.list"
  { printf "$hdr"; for f in "$nngsrc"/src/platform/windows/*.c; do
      b=$(basename "$f" .c); printf '$(NNG)/platform/windows/%s.o\n' "$b"; done; } > "$TOOLS/nng_windows.list"
}

if [ "$VERIFY" -eq 1 ]; then
  echo "=== Verifying NNG source lists against cmake oracle ($VERSION) ==="
  ORACLE=$(get_oracle_dir)
  # The Mbed TLS engine is always bundled but absent from the engine-less oracle.
  objs=$( { oracle_objects "$ORACLE"; printf '%s\n' "$TLS_ENGINE_OBJECT"; } | sort -u)
  always=$( { read_list "$TOOLS/nng_common.list"; read_list "$TOOLS/nng_posix.list"; } | sort -u)
  variants=$( { read_list "$TOOLS/nng_pollers.list"; read_list "$TOOLS/nng_rand.list"; } | sort -u)
  allknown=$(printf '%s\n%s\n' "$always" "$variants" | sort -u)

  rc=0
  # (1) Every object the oracle compiles must have a known rule.
  missing=$(comm -23 <(printf '%s\n' "$objs") <(printf '%s\n' "$allknown"))
  if [ -n "$missing" ]; then
    echo "NEW upstream object(s) not in any tools/nng_*.list (add them):"
    printf '  %s\n' $missing; rc=1
  fi
  # (2) Every always-on object must still be compiled upstream.
  stale=$(comm -23 <(printf '%s\n' "$always") <(printf '%s\n' "$objs"))
  if [ -n "$stale" ]; then
    echo "Object in nng_common/nng_posix no longer compiled upstream (remove it):"
    printf '  %s\n' $stale; rc=1
  fi
  [ -n "$WORK" ] && rm -rf "$WORK"
  [ "$rc" -eq 0 ] && echo "OK: source lists match the oracle." || echo "DRIFT detected."
  exit $rc
fi

# --- Full refresh -----------------------------------------------------------
WORK=$(mktemp -d)
echo "Cloning NNG ($VERSION) ..."
git clone --quiet "$NNG_REPO" "$WORK/nng"
git -C "$WORK/nng" checkout --quiet "$VERSION"
echo "Building cmake oracle (for source-list derivation) ..."
build_oracle "$WORK/nng" "$WORK/build"

echo "Staging sources (stripping cmake / build infrastructure) ..."
STAGE="$WORK/stage"
mkdir -p "$STAGE"
cp -R "$WORK/nng/src" "$STAGE/"
cp -R "$WORK/nng/include" "$STAGE/"
cp "$WORK/nng/LICENSE.txt" "$STAGE/" 2>/dev/null || true
# Strip every cmake / autotools artifact: we compile in place.
find "$STAGE" -name 'CMakeLists.txt' -delete
find "$STAGE" -type d -name cmake -exec rm -rf {} + 2>/dev/null || true
find "$STAGE" \( -name '*.cmake' -o -name '*.cmake.in' \) -delete 2>/dev/null || true
# Drop the sources nanonext does not bundle (mirror of PRUNE_RE): deprecated
# compat API, unused TLS/transport back-ends, unit tests, and NNG's tools / test
# framework. Keeps the vendored tree to the set nanonext actually compiles.
rm -f  "$STAGE/src/nng_legacy.c"
rm -rf "$STAGE/src/compat" "$STAGE/src/testing" "$STAGE/src/tools"
rm -rf "$STAGE/src/sp/transport/zerotier"
rm -rf "$STAGE/src/supplemental/tls/wolfssl"
rm -rf "$STAGE/include/nng/compat"
rm -rf "$STAGE/include/nng/transport/zerotier"
find "$STAGE" \( -name '*_test.c' -o -name '*_test.h' \) -delete
# Drop stray documentation that rides along in the source tree (README.adoc, ...).
find "$STAGE" \( -name '*.adoc' -o -name '*.md' -o -name 'README*' \) -delete

# Strip non-license comments so the vendored tree carries only the // license
# header. Keeps the sources lean and focuses the diff against a fresh upstream
# checkout on real code.
echo "Stripping non-license comments ..."
find "$STAGE" -type f \( -name '*.c' -o -name '*.h' \) | while IFS= read -r f; do
  perl "$TOOLS/strip_comments.pl" < "$f" > "$f.stripped" && mv "$f.stripped" "$f"
done

echo "Replacing src/nng ..."
rm -rf "$PKG_ROOT/src/nng"
mkdir -p "$PKG_ROOT/src/nng"
cp -R "$STAGE/." "$PKG_ROOT/src/nng/"

echo "Applying patches ..."
"$TOOLS/patch_nng.sh" "$PKG_ROOT/src/nng/src"

echo "Regenerating source lists + Makevars ..."
write_lists "$WORK/build" "$PKG_ROOT/src/nng"
sh "$TOOLS/generate_makevars.sh"

rm -rf "$WORK"
echo "=== NNG update complete ($VERSION) ==="
