#!/bin/bash

# Vendor / refresh the bundled NNG sources and regenerate the build files.
#
# Usage:
#   ./tools/update_nng.sh [VERSION]     refresh src/nng from upstream VERSION
#   ./tools/update_nng.sh --verify [VERSION]
#                                       check the committed source lists against
#                                       a fresh cmake "oracle" build (no writes)
#
# The bundled NNG compiles directly into nanonext.so via the per-object rules in
# src/Makevars*. cmake is used here ONLY as the verification oracle for the
# object set (export of compile_commands.json) -- it is not part of the package
# build. This script is the maintenance contract: it derives the authoritative
# tools/nng_*.list source lists from that oracle, applies tools/patch_nng.sh, and
# regenerates the three Makevars via tools/generate_makevars.sh.
#
# The NNG option set must match the package build: all protocols & transports on,
# TLS = mbed, stats on -- these are NNG's CMake defaults, so a plain configure of
# upstream reproduces nanonext's compiled object set.
#
# For offline testing the oracle build dir can be supplied via NNG_ORACLE_DIR
# (must contain compile_commands.json); the upstream clone/cmake steps are then
# skipped.

set -e

NNG_REPO="https://github.com/nanomsg/nng.git"
# Pinned upstream ref. Update together with the vendored tree.
NNG_DEFAULT_VERSION="v1.11.0"

PKG_ROOT=$(cd "$(dirname "$0")/.." && pwd)
TOOLS="$PKG_ROOT/tools"

VERIFY=0
VERSION=""
for arg in "$@"; do
  case "$arg" in
    --verify) VERIFY=1 ;;
    *) VERSION="$arg" ;;
  esac
done
[ -n "$VERSION" ] || VERSION="$NNG_DEFAULT_VERSION"

# Normalise a compile_commands.json into the sorted set of compiled objects in
# $(NNG)/<path>.o form (paths relative to nng/src). Reads the build dir's
# compile_commands.json; emits one object per line.
oracle_objects() {
  grep '"file"' "$1/compile_commands.json" |
    sed -E 's/.*"file"[[:space:]]*:[[:space:]]*"([^"]+)".*/\1/' |
    sed -E 's#.*/src/nng/src/##' |
    grep -E '\.c$' |
    sed -E 's#\.c$#.o#; s#^#\$(NNG)/#' |
    sort -u
}

# Build the cmake oracle for a checked-out NNG tree into $2.
build_oracle() {
  src=$1; bld=$2
  CC=`"${R_HOME:-$(R RHOME)}/bin/R" CMD config CC 2>/dev/null || echo cc`
  export CC
  cmake -S "$src" -B "$bld" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_BUILD_TYPE=Release >/dev/null 2>&1
}

read_list() { grep -v '^#' "$1" | grep -v '^[[:space:]]*$'; }

# Obtain an oracle build dir (clone + cmake, unless NNG_ORACLE_DIR supplied).
WORK=""
get_oracle_dir() {
  if [ -n "$NNG_ORACLE_DIR" ]; then
    echo "$NNG_ORACLE_DIR"
    return
  fi
  WORK=$(mktemp -d)
  echo "Cloning NNG $VERSION ..." >&2
  git clone --depth 1 --branch "$VERSION" "$NNG_REPO" "$WORK/nng" >/dev/null 2>&1
  echo "Configuring cmake oracle ..." >&2
  build_oracle "$WORK/nng" "$WORK/build"
  echo "$WORK/build"
}

# Categorise the oracle object set and (re)write tools/nng_*.list. $1 = oracle
# dir, $2 = checked-out NNG src tree (for globbing poller/rand/windows variants).
write_lists() {
  oracle=$1; nngsrc=$2
  objs=$(oracle_objects "$oracle")

  common=$(printf '%s\n' "$objs" | grep -v '\$(NNG)/platform/')
  posix=$(printf '%s\n' "$objs" | grep '\$(NNG)/platform/posix/' | grep -vE 'posix_pollq_|posix_rand_')

  hdr="# Generated by tools/update_nng.sh -- single source of truth for the build.\n# Object paths use the \$(NNG) make variable. Do not edit by hand.\n"

  printf "$hdr%s\n" "$common" > "$TOOLS/nng_common.list"
  printf "$hdr%s\n" "$posix"  > "$TOOLS/nng_posix.list"
  # Poller / rand / windows variants: every variant present in the tree (the
  # build selects one poller + one rand at configure time; rules exist for all).
  { printf "$hdr"; for f in "$nngsrc"/src/platform/posix/posix_pollq_*.c; do
      b=$(basename "$f" .c); printf '$(NNG)/platform/posix/%s.o\n' "$b"; done; } > "$TOOLS/nng_pollers.list"
  { printf "$hdr"; for f in "$nngsrc"/src/platform/posix/posix_rand_*.c; do
      b=$(basename "$f" .c); printf '$(NNG)/platform/posix/%s.o\n' "$b"; done; } > "$TOOLS/nng_rand.list"
  { printf "$hdr"; for f in "$nngsrc"/src/platform/windows/*.c; do
      b=$(basename "$f" .c); printf '$(NNG)/platform/windows/%s.o\n' "$b"; done; } > "$TOOLS/nng_windows.list"
}

if [ "$VERIFY" -eq 1 ]; then
  echo "=== Verifying NNG source lists against cmake oracle ($VERSION) ==="
  ORACLE=$(get_oracle_dir)
  objs=$(oracle_objects "$ORACLE")
  always=$( { read_list "$TOOLS/nng_common.list"; read_list "$TOOLS/nng_posix.list"; } | sort -u)
  variants=$( { read_list "$TOOLS/nng_pollers.list"; read_list "$TOOLS/nng_rand.list"; } | sort -u)
  allknown=$(printf '%s\n%s\n' "$always" "$variants" | sort -u)

  rc=0
  # (1) Every object the oracle compiles must have a known rule.
  missing=$(comm -23 <(printf '%s\n' "$objs") <(printf '%s\n' "$allknown"))
  if [ -n "$missing" ]; then
    echo "NEW upstream object(s) not in any tools/nng_*.list (add them):"
    printf '  %s\n' $missing; rc=1
  fi
  # (2) Every always-on object must still be compiled upstream.
  stale=$(comm -23 <(printf '%s\n' "$always") <(printf '%s\n' "$objs"))
  if [ -n "$stale" ]; then
    echo "Object in nng_common/nng_posix no longer compiled upstream (remove it):"
    printf '  %s\n' $stale; rc=1
  fi
  [ -n "$WORK" ] && rm -rf "$WORK"
  [ "$rc" -eq 0 ] && echo "OK: source lists match the oracle." || echo "DRIFT detected."
  exit $rc
fi

# --- Full refresh -----------------------------------------------------------
WORK=$(mktemp -d)
echo "Cloning NNG $VERSION ..."
git clone --depth 1 --branch "$VERSION" "$NNG_REPO" "$WORK/nng" >/dev/null 2>&1
echo "Building cmake oracle (for source-list derivation) ..."
build_oracle "$WORK/nng" "$WORK/build"

echo "Staging sources (stripping cmake / build infrastructure) ..."
STAGE="$WORK/stage"
mkdir -p "$STAGE"
cp -R "$WORK/nng/src" "$STAGE/"
cp -R "$WORK/nng/include" "$STAGE/"
cp "$WORK/nng/LICENSE.txt" "$STAGE/" 2>/dev/null || true
# Strip every cmake / autotools artifact: we compile in place.
find "$STAGE" -name 'CMakeLists.txt' -delete
find "$STAGE" -type d -name cmake -exec rm -rf {} + 2>/dev/null || true
find "$STAGE" -name '*.cmake' -o -name '*.cmake.in' -delete 2>/dev/null || true

echo "Replacing src/nng ..."
rm -rf "$PKG_ROOT/src/nng"
mkdir -p "$PKG_ROOT/src/nng"
cp -R "$STAGE/." "$PKG_ROOT/src/nng/"

echo "Applying patches ..."
"$TOOLS/patch_nng.sh" "$PKG_ROOT/src/nng/src"

echo "Regenerating source lists + Makevars ..."
write_lists "$WORK/build" "$PKG_ROOT/src/nng"
sh "$TOOLS/generate_makevars.sh"

rm -rf "$WORK"
echo "=== NNG update complete ($VERSION) ==="
