#!/bin/bash

# Vendor / refresh the bundled Mbed TLS sources and regenerate the build files.
#
# Usage:
#   ./tools/update_mbedtls.sh [VERSION]    refresh src/mbedtls from upstream
#   ./tools/update_mbedtls.sh --verify [VERSION]
#                                          check tools/mbedtls.list against a
#                                          fresh cmake "oracle" build (no writes)
#
# The bundled Mbed TLS compiles directly into nanonext.so via the per-object
# rules in src/Makevars*. cmake is used here ONLY as the verification oracle for
# the object set; it is not part of the package build. The committed
# include/mbedtls/mbedtls_config.h drives the feature set (the two historically
# generated files error.c and ssl_debug_helpers_generated.c are committed; no
# build-time generation). tools/patch_mbedtls.sh is applied after vendoring.
#
# For offline testing the oracle build dir can be supplied via MBEDTLS_ORACLE_DIR
# (must contain compile_commands.json); the clone/cmake steps are then skipped.

set -e

MBEDTLS_REPO="https://github.com/Mbed-TLS/mbedtls.git"
MBEDTLS_DEFAULT_VERSION="v3.6.5"

PKG_ROOT=$(cd "$(dirname "$0")/.." && pwd)
TOOLS="$PKG_ROOT/tools"

VERIFY=0
VERSION=""
for arg in "$@"; do
  case "$arg" in
    --verify) VERIFY=1 ;;
    *) VERSION="$arg" ;;
  esac
done
[ -n "$VERSION" ] || VERSION="$MBEDTLS_DEFAULT_VERSION"

# Normalise compile_commands.json -> sorted set of $(MBED)/<file>.o (paths
# relative to mbedtls/library).
oracle_objects() {
  grep '"file"' "$1/compile_commands.json" |
    sed -E 's/.*"file"[[:space:]]*:[[:space:]]*"([^"]+)".*/\1/' |
    sed -E 's#.*/src/mbedtls/library/##' |
    grep -E '\.c$' |
    sed -E 's#\.c$#.o#; s#^#\$(MBED)/#' |
    sort -u
}

build_oracle() {
  src=$1; bld=$2
  CC=`"${R_HOME:-$(R RHOME)}/bin/R" CMD config CC 2>/dev/null || echo cc`
  export CC
  cmake -S "$src" -B "$bld" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_INSTALL_LIBDIR=lib >/dev/null 2>&1
}

read_list() { grep -v '^#' "$1" | grep -v '^[[:space:]]*$'; }

WORK=""
get_oracle_dir() {
  if [ -n "$MBEDTLS_ORACLE_DIR" ]; then echo "$MBEDTLS_ORACLE_DIR"; return; fi
  WORK=$(mktemp -d)
  echo "Cloning Mbed TLS $VERSION ..." >&2
  git clone --depth 1 --branch "$VERSION" "$MBEDTLS_REPO" "$WORK/mbedtls" >/dev/null 2>&1
  (cd "$WORK/mbedtls" && git submodule update --init >/dev/null 2>&1 || true)
  echo "Configuring cmake oracle ..." >&2
  build_oracle "$WORK/mbedtls" "$WORK/build"
  echo "$WORK/build"
}

if [ "$VERIFY" -eq 1 ]; then
  echo "=== Verifying Mbed TLS source list against cmake oracle ($VERSION) ==="
  ORACLE=$(get_oracle_dir)
  objs=$(oracle_objects "$ORACLE")
  known=$(read_list "$TOOLS/mbedtls.list" | sort -u)
  rc=0
  missing=$(comm -23 <(printf '%s\n' "$objs") <(printf '%s\n' "$known"))
  stale=$(comm -13 <(printf '%s\n' "$objs") <(printf '%s\n' "$known"))
  if [ -n "$missing" ]; then echo "NEW upstream object(s) not in tools/mbedtls.list:"; printf '  %s\n' $missing; rc=1; fi
  if [ -n "$stale" ];   then echo "Object in tools/mbedtls.list not compiled upstream:"; printf '  %s\n' $stale; rc=1; fi
  [ -n "$WORK" ] && rm -rf "$WORK"
  [ "$rc" -eq 0 ] && echo "OK: source list matches the oracle." || echo "DRIFT detected."
  exit $rc
fi

# --- Full refresh -----------------------------------------------------------
WORK=$(mktemp -d)
echo "Cloning Mbed TLS $VERSION ..."
git clone --depth 1 --branch "$VERSION" "$MBEDTLS_REPO" "$WORK/mbedtls" >/dev/null 2>&1
(cd "$WORK/mbedtls" && git submodule update --init >/dev/null 2>&1 || true)
echo "Building cmake oracle (for source-list derivation) ..."
build_oracle "$WORK/mbedtls" "$WORK/build"

echo "Staging sources (stripping cmake / build infrastructure) ..."
STAGE="$WORK/stage"
mkdir -p "$STAGE"
cp -R "$WORK/mbedtls/library" "$STAGE/"
cp -R "$WORK/mbedtls/include" "$STAGE/"
cp "$WORK/mbedtls/LICENSE" "$STAGE/" 2>/dev/null || true
find "$STAGE" -name 'CMakeLists.txt' -delete
find "$STAGE" -type d -name cmake -exec rm -rf {} + 2>/dev/null || true
find "$STAGE" \( -name '*.cmake' -o -name '*.cmake.in' \) -delete 2>/dev/null || true

echo "Replacing src/mbedtls ..."
rm -rf "$PKG_ROOT/src/mbedtls"
mkdir -p "$PKG_ROOT/src/mbedtls"
cp -R "$STAGE/." "$PKG_ROOT/src/mbedtls/"

echo "Applying patches ..."
"$TOOLS/patch_mbedtls.sh" "$PKG_ROOT/src/mbedtls"

echo "Regenerating source list + Makevars ..."
hdr="# Generated by tools/update_mbedtls.sh -- single source of truth for the build.\n# Object paths use the \$(MBED) make variable. Do not edit by hand.\n"
printf "$hdr%s\n" "$(oracle_objects "$WORK/build")" > "$TOOLS/mbedtls.list"
sh "$TOOLS/generate_makevars.sh"

rm -rf "$WORK"
echo "=== Mbed TLS update complete ($VERSION) ==="
